version: 0.2

env:
  variables:
    IMAGE_TAG: "no_version"

phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
        - export IMAGE_TAG=latest
    build:
      commands:
        - echo Build started on `date`
        - echo Building the Docker image version $IMAGE_TAG ...
        - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/omicflows-landing:latest .
        - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/omicflows-landing:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/omicflows-landing:$IMAGE_TAG
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/omicflows-landing:latest

artifacts:
  files:
    - 'stop_server.sh'
    - 'start_server.sh'
    - 'check_service.sh'
    - 'appspec.yml'
    - 'docker-compose.production.yml'
